### ISSUE TITLE
Browser wasm compatibility request

### ISSUE THREAD

**Issue by shravanshetty1** [oasisprotocol/curve25519-voi#95]
Cant seem to find another library that supports ZIP 215 in golang that is also wasm compatible.

**Comment by Yawning** [comment]
Well, you closed this for some reason, but I'll respond so I can refer to this when other people ask for it.

https://github.com/hdevalence/ed25519consensus should work, but performance will be bad, primarily because wasm doesn't have a proper 64-bit multiply.  There are a few other issues with the Go compiler and the underlying field/scalar library as well.

That said, I am reluctant to support WASM because operations that work on secret data are unsafe, and will remain unsafe until something like the [Constant-Time Integer Operations](https://github.com/WebAssembly/constant-time/blob/master/proposals/constant-time/Overview.md) extension is adopted, implemented, and used by the compiler.

While I could split out all the operations for the higher level primitives that operate on secret data into their own files, and use build tags to disable them on a wasm target, that is more work than I am willing to do at this time.

**Comment by shravanshetty1** [comment]
For people who need wasm can maybe use this - https://github.com/hdevalence/ed25519consensus.

Closed the issue since I found a ZIP 215 golang lib.

Thank you!
